name: openai-clip
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - pytorch=2.3.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # Automatically installs the right CUDA toolkit
  - pip:
      - ftfy
      - regex
      - tensorboard
      - requests
      - google-auth
      - google-auth-oauthlib
      - wandb
      - torch-geometric
      - ogb
      - git+https://github.com/modestyachts/ImageNetV2_pytorch
      - https://pytorch-geometric.com/whl/torch-2.3.0+cu121/torch_scatter-2.1.2-cp310-cp310-linux_x86_64.whl
